version: "1.0"

# Configuração do DocSync para o projeto XadrezMaster
source_directories:
  - docs/tecnico
  - docs/analise
  - docs/arquitetura
  - docs/produto

# Padrões de arquivos a serem sincronizados
patterns:
  - "*.md"
  - "*.txt"

# Configurações de sincronização
sync:
  backup_dir: ".backup/docs"
  versioning: true
  language:
    primary: "pt-BR"
    fallback: "en"

# Validações
validate:
  structure:
    - check_headers
    - check_links
    - check_metadata
  content:
    - spell_check
    - lint_markdown

# Templates padrão
templates:
  technical:
    path: "docs/templates/technical.md"
    required_sections:
      - "## Visão Geral"
      - "## Especificações Técnicas"
      - "## Implementação"
  analysis:
    path: "docs/templates/analysis.md"
    required_sections:
      - "## Objetivo"
      - "## Metodologia"
      - "## Resultados"
      - "## Conclusões"
