name: Bug report
description: File a bug report
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen
      placeholder: Tell us what you see!
      value: |
        A bug happened!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: CHESS version or commit hash
      placeholder: v0.2.0
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      render: shell
