name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: proposal
    attributes:
      label: What problem are you trying to solve?
      description: A clear and concise description of the problem.
      placeholder: I'd like to...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Cultural System
        - AI/ARKITECT
        - Quantum Engine
        - UI/Audio
        - Deployment/CI
        - Documentation
  - type: textarea
    id: extra
    attributes:
      label: Additional context

