version: "1.0"

# Configuração do DocSync para o Banco de Dados Cultural do ChessMaster
name: "cultural_database_sync"
description: "Sincronização e organização do banco de dados cultural do ChessMaster"

# Diretórios fonte
source_directories:
  - research
  - configurations
  - content

# Padrões de arquivos
patterns:
  - "*.md"    # Documentação e narrativas
  - "*.yaml"  # Configurações
  - "*.json"  # Dados estruturados

# Configurações de sincronização
sync:
  backup_dir: "../.backup/cultural_data"
  versioning: true
  automated: true
  interval: 3600  # 1 hora
  language:
    primary: "pt-BR"
    fallback: "en"
    technical_terms: "maintain_original"

# Validações
validate:
  structure:
    - check_directory_structure
    - check_file_naming
    - check_required_files
  content:
    - validate_yaml
    - validate_markdown
    - check_cultural_references
    - spell_check:
        language: "pt-BR"
        technical_terms: true
  metadata:
    - check_required_fields
    - validate_cultural_tags
    - validate_relationships

# Templates
templates:
  cultural_theme:
    path: "templates/theme.yaml"
    required_fields:
      - name
      - type
      - attributes
      - narrative_elements
    optional_fields:
      - visual_theme
      - sound_effects
      
  cultural_pieces:
    path: "templates/pieces.yaml"
    required_fields:
      - name
      - culture
      - pieces
    optional_fields:
      - visual_theme
      - sound_effects
      
  cultural_lesson:
    path: "templates/lesson.md"
    required_sections:
      - "## Visão Geral"
      - "## Elementos Culturais"
      - "## Estratégias Culturalmente Contextualizadas"
      - "## Filosofia do Jogo"
      - "## Aplicações Práticas"
      
  cultural_story:
    path: "templates/story.md"
    required_sections:
      - "## Prólogo"
      - "## Desenvolvimento"
      - "## Clímax"
      - "## Epílogo"
      - "## Elementos Culturais"
      
  cultural_research:
    path: "templates/research.md"
    required_sections:
      - "## Introdução"
      - "## Contexto Histórico"
      - "## Análise"
      - "## Conclusão"
      - "## Referências"

# Integrações
integrations:
  notion:
    enabled: true
    sync_interval: 3600
    collections:
      - cultural_research
      - cultural_stories
      - cultural_lessons
  
  nexus:
    enabled: true
    connectors:
      - taskmash:
          enabled: true
          task_types: ["cultural_development", "content_creation"]
      - docsync:
          enabled: true
          sync_types: ["cultural_database"]
      - arkitect:
          enabled: true
          analysis_types: ["cultural_structure"]

# Automações
automations:
  - name: "template_generation"
    trigger: "on_new_culture"
    actions:
      - generate_theme_config
      - generate_pieces_config
      - generate_lesson_template
      - generate_story_template
      - generate_research_template
      
  - name: "content_validation"
    trigger: "on_file_change"
    actions:
      - validate_structure
      - validate_content
      - validate_relationships
      
  - name: "backup_creation"
    trigger: "daily"
    actions:
      - create_full_backup
      - validate_backup
      - clean_old_backups

# Métricas e Monitoramento
monitoring:
  metrics:
    - content_completeness
    - cultural_coverage
    - template_usage
    - validation_success_rate
  
  alerts:
    - validation_failure
    - sync_failure
    - backup_failure
    
  reports:
    daily:
      - content_status
      - validation_summary
      - sync_status
    weekly:
      - cultural_coverage_report
      - template_usage_analysis
      - validation_trends

# Manutenção
maintenance:
  cleanup:
    - old_backups:
        retention: "30d"
    - validation_logs:
        retention: "7d"
    - temp_files:
        retention: "1d"
  
  optimization:
    - compact_storage:
        trigger: "weekly"
    - reindex_content:
        trigger: "daily"
